# Describes the format for available counter services

decrement:
  description: Decrement a counter.
  fields:
    entity_id:
      description: Entity id of the counter to decrement.
      example: 'counter.count0'
increment:
  description: Increment a counter.
  fields:
    entity_id:
      description: Entity id of the counter to increment.
      example: 'counter.count0'
reset:
  description: Reset a counter.
  fields:
    entity_id:
      description: Entity id of the counter to reset.
      example: 'counter.count0'